### ISSUE TITLE
Maximum call stack size exceeded when trying to convert `pixi.js` v8.

### ISSUE THREAD

**Issue by Ayfri** [karakum-team/karakum#11]
Hello, I'm trying to convert [`PIXI.js`](https://github.com/pixijs/pixijs) v8 with the following configuration :
```json
{
	"input": "node_modules/pixi.js/lib/**/*.d.ts",
	"output": "dist",
	"libraryName": "pixi.js"
}
```
But I'm getting the following error :
```
file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17
    return commonPrefix(common, ...rest);
           ^

RangeError: Maximum call stack size exceeded
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
    at commonPrefix (file:///C:/Users/MyUser/IdeaProjects/random/karakum-test/node_modules/karakum/build/utils/fileName.js:17:12)
```

Here is my `package.json` : 

```json
{
	"name": "karakum-test",
	"version": "1.0.0",
	"scripts": {
		"start": "karakum --config karakum.config.json"
	},
	"dependencies": {
		"pixi.js": "^8.0.0-beta.6"
	},
	"devDependencies": {
		"karakum": "^1.0.0-alpha.25",
		"typescript": "^5.2.2"
	}
}
```

**Comment by sgrishchenko** [comment]
Thank you for the report. I will check what is wrong with this `commonPrefix` helper.

**Comment by sgrishchenko** [comment]
@Ayfri I removed recursion in the `commonPrefix` helper. It is used only for detection of common file root that can be set up manually using `inputRoots` config option, so also now I compute common root lazily only if `inputRoots` is not specified. All changes are published, so you can check them.

But to be honest, I didn't reproduce your problem. After running of Karakum for your setup, I received only two files
```
/dist/filters.kt
/dist/index.kt
```
I noticed that `index.kt` re-exports a lot of stuff, so maybe the number of reexported files causes the issue with recursion?
It would be great if you provide more details about your conversion. Maybe I will even add you configs as an example in Karakum repository.

**Comment by sgrishchenko** [comment]
Sorry, I used `v7` of [PIXI.js](https://github.com/pixijs/pixijs), that is why the number of files was so small. I tested it with  `v8` and now I see, the number of files is really big. I still didn't reproduce it on Linux (I don't know why), but I will try to do it on Windows later.

**Comment by Ayfri** [comment]
@sgrishchenko Have you had time to test ?

**Comment by sgrishchenko** [comment]
No, I didn't yet, but I already published a fix, that should solve this issue. You can try a new Karakum version.
